[project]
name = "arrayview"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.3",
    "nibabel>=5.3.2",
    "numpy>=2.3.1",
    "pyqt5>=5.15.11",
]

[project.scripts]
arrayview = "arrayview.cli:main"
