[project]
name = "arrayview"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "h5py>=3.14.0",
    "matplotlib>=3.10.3",
    "nibabel>=5.3.2",
    "numpy>=2.3.1",
    "pyqt5>=5.15.11",
    "qmricolors",
    "scipy>=1.16.2",
]

[project.scripts]
arrayview = "cli:main"

[tool.uv.sources]
qmricolors = { git = "https://github.com/oscarvanderheide/qmricolors.git" }
